#server port number
server:
  port: 9999

#oracle config properties
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: manager
    driver-class-name: oracle.jdbc.driver.OracleDriver
    
 #hibernate properties
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        show_sql: true
        format_sql: true
        
    
#view resolver # application.yml
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  mail:
    host: smtp.gmail.com
    port: 587
    username:  posaraghu090909@gmail.com
    password:  Abdul@1994
    properties:
      mail:
        smtp:
         starttls:
           enable: true
           required: true
         auth: true  
         connectiontimeout: 10000
         timeout: 10000
         writetimeout: 10000
     
 

#messages
his: 
  enrollSuccess: Enrollment successfull
  enrollFailure: Enrollment Failure  
  userRegistration: userRegistration    
  message: message
          
